// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqHdKU40mozbZBLxTDe5YzhimJhFX3vaw',
    appId: '1:296491821159:web:66697524244d1be0d4ccc2',
    messagingSenderId: '296491821159',
    projectId: 'elevateappv2',
    authDomain: 'elevateappv2.firebaseapp.com',
    storageBucket: 'elevateappv2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEdm5U8VWrONWvnokg5nH5LnrKed-2Lqk',
    appId: '1:296491821159:android:3e26ec9576996041d4ccc2',
    messagingSenderId: '296491821159',
    projectId: 'elevateappv2',
    storageBucket: 'elevateappv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfxBjcrRpDIiq0bblRP4VoxPt3qeBZFcw',
    appId: '1:296491821159:ios:29378badc589a988d4ccc2',
    messagingSenderId: '296491821159',
    projectId: 'elevateappv2',
    storageBucket: 'elevateappv2.firebasestorage.app',
    iosBundleId: 'com.example.elevateAppV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfxBjcrRpDIiq0bblRP4VoxPt3qeBZFcw',
    appId: '1:296491821159:ios:29378badc589a988d4ccc2',
    messagingSenderId: '296491821159',
    projectId: 'elevateappv2',
    storageBucket: 'elevateappv2.firebasestorage.app',
    iosBundleId: 'com.example.elevateAppV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqHdKU40mozbZBLxTDe5YzhimJhFX3vaw',
    appId: '1:296491821159:web:639c0c4b8a14d4dcd4ccc2',
    messagingSenderId: '296491821159',
    projectId: 'elevateappv2',
    authDomain: 'elevateappv2.firebaseapp.com',
    storageBucket: 'elevateappv2.firebasestorage.app',
  );
}
